package com.ssafy.edu.employee.model;

import java.math.BigDecimal;
import java.util.Date;

import com.ssafy.edu.test.EmployeeDTO;

public class Employees {

	
	public Employees() {
		super();
		// TODO Auto-generated constructor stub
	}
	public Employees(EmployeeDTO dto) {
		this(dto.getEmployeeId(), dto.getFirstName(), dto.getLastName(), dto.getEmail(),
				dto.getPhoneNumber(),dto.getHireDate(),dto.getJobId(),dto.getSalary(),
				dto.getCommissionPct(),dto.getManagerId(), dto.getDepartmentId());
	}
	public Employees(Integer employeeId, String firstName, String lastName,
			String email, String phoneNumber,
			Date hireDate, String jobId, 
			BigDecimal salary, BigDecimal commissionPct, Integer managerId,
			Integer departmentId) {
		super();
		this.employeeId = employeeId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.phoneNumber = phoneNumber;
		this.hireDate = hireDate;
		this.jobId = jobId;
		this.salary = salary;
		this.commissionPct = commissionPct;
		this.managerId = managerId;
		this.departmentId = departmentId;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employees.employee_id
	 * @mbg.generated
	 */
	private Integer employeeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employees.first_name
	 * @mbg.generated
	 */
	private String firstName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employees.last_name
	 * @mbg.generated
	 */
	private String lastName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employees.email
	 * @mbg.generated
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employees.phone_number
	 * @mbg.generated
	 */
	private String phoneNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employees.hire_date
	 * @mbg.generated
	 */
	private Date hireDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employees.job_id
	 * @mbg.generated
	 */
	private String jobId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employees.salary
	 * @mbg.generated
	 */
	private BigDecimal salary;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employees.commission_pct
	 * @mbg.generated
	 */
	private BigDecimal commissionPct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employees.manager_id
	 * @mbg.generated
	 */
	private Integer managerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employees.department_id
	 * @mbg.generated
	 */
	private Integer departmentId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employees.employee_id
	 * @return  the value of employees.employee_id
	 * @mbg.generated
	 */
	public Integer getEmployeeId() {
		return employeeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employees.employee_id
	 * @param employeeId  the value for employees.employee_id
	 * @mbg.generated
	 */
	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employees.first_name
	 * @return  the value of employees.first_name
	 * @mbg.generated
	 */
	public String getFirstName() {
		return firstName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employees.first_name
	 * @param firstName  the value for employees.first_name
	 * @mbg.generated
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName == null ? null : firstName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employees.last_name
	 * @return  the value of employees.last_name
	 * @mbg.generated
	 */
	public String getLastName() {
		return lastName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employees.last_name
	 * @param lastName  the value for employees.last_name
	 * @mbg.generated
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName == null ? null : lastName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employees.email
	 * @return  the value of employees.email
	 * @mbg.generated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employees.email
	 * @param email  the value for employees.email
	 * @mbg.generated
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employees.phone_number
	 * @return  the value of employees.phone_number
	 * @mbg.generated
	 */
	public String getPhoneNumber() {
		return phoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employees.phone_number
	 * @param phoneNumber  the value for employees.phone_number
	 * @mbg.generated
	 */
	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employees.hire_date
	 * @return  the value of employees.hire_date
	 * @mbg.generated
	 */
	public Date getHireDate() {
		return hireDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employees.hire_date
	 * @param hireDate  the value for employees.hire_date
	 * @mbg.generated
	 */
	public void setHireDate(Date hireDate) {
		this.hireDate = hireDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employees.job_id
	 * @return  the value of employees.job_id
	 * @mbg.generated
	 */
	public String getJobId() {
		return jobId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employees.job_id
	 * @param jobId  the value for employees.job_id
	 * @mbg.generated
	 */
	public void setJobId(String jobId) {
		this.jobId = jobId == null ? null : jobId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employees.salary
	 * @return  the value of employees.salary
	 * @mbg.generated
	 */
	public BigDecimal getSalary() {
		return salary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employees.salary
	 * @param salary  the value for employees.salary
	 * @mbg.generated
	 */
	public void setSalary(BigDecimal salary) {
		this.salary = salary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employees.commission_pct
	 * @return  the value of employees.commission_pct
	 * @mbg.generated
	 */
	public BigDecimal getCommissionPct() {
		return commissionPct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employees.commission_pct
	 * @param commissionPct  the value for employees.commission_pct
	 * @mbg.generated
	 */
	public void setCommissionPct(BigDecimal commissionPct) {
		this.commissionPct = commissionPct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employees.manager_id
	 * @return  the value of employees.manager_id
	 * @mbg.generated
	 */
	public Integer getManagerId() {
		return managerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employees.manager_id
	 * @param managerId  the value for employees.manager_id
	 * @mbg.generated
	 */
	public void setManagerId(Integer managerId) {
		this.managerId = managerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employees.department_id
	 * @return  the value of employees.department_id
	 * @mbg.generated
	 */
	public Integer getDepartmentId() {
		return departmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employees.department_id
	 * @param departmentId  the value for employees.department_id
	 * @mbg.generated
	 */
	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", employeeId=").append(employeeId);
		sb.append(", firstName=").append(firstName);
		sb.append(", lastName=").append(lastName);
		sb.append(", email=").append(email);
		sb.append(", phoneNumber=").append(phoneNumber);
		sb.append(", hireDate=").append(hireDate);
		sb.append(", jobId=").append(jobId);
		sb.append(", salary=").append(salary);
		sb.append(", commissionPct=").append(commissionPct);
		sb.append(", managerId=").append(managerId);
		sb.append(", departmentId=").append(departmentId);
		sb.append("]");
		return sb.toString();
	}
}