package com.ssafy.edu.employee.model.mapper;

import com.ssafy.edu.employee.model.Employees;
import com.ssafy.edu.employee.model.EmployeesExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
@Mapper
public interface EmployeesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated
	 */
	long countByExample(EmployeesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated
	 */
	int deleteByExample(EmployeesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer employeeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated
	 */
	int insert(Employees row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated
	 */
	int insertSelective(Employees row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated
	 */
	List<Employees> selectByExampleWithRowbounds(EmployeesExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated
	 */
	List<Employees> selectByExample(EmployeesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated
	 */
	Employees selectByPrimaryKey(Integer employeeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") Employees row, @Param("example") EmployeesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") Employees row, @Param("example") EmployeesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Employees row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Employees row);

	List<Employees> findByPagingAndSearch(EmployeesExample empcriteria);

	List<Employees> selectByExampleWithLimit(@Param("example")  EmployeesExample example, @Param("limit")  int limit, @Param("offset")  int offset);
}