package com.ssafy.edu.department.model;

public class Departments {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column departments.department_id
	 * @mbg.generated
	 */
	private Integer departmentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column departments.department_name
	 * @mbg.generated
	 */
	private String departmentName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column departments.manager_id
	 * @mbg.generated
	 */
	private Integer managerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column departments.location_id
	 * @mbg.generated
	 */
	private Integer locationId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column departments.department_id
	 * @return  the value of departments.department_id
	 * @mbg.generated
	 */
	public Integer getDepartmentId() {
		return departmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column departments.department_id
	 * @param departmentId  the value for departments.department_id
	 * @mbg.generated
	 */
	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column departments.department_name
	 * @return  the value of departments.department_name
	 * @mbg.generated
	 */
	public String getDepartmentName() {
		return departmentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column departments.department_name
	 * @param departmentName  the value for departments.department_name
	 * @mbg.generated
	 */
	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName == null ? null : departmentName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column departments.manager_id
	 * @return  the value of departments.manager_id
	 * @mbg.generated
	 */
	public Integer getManagerId() {
		return managerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column departments.manager_id
	 * @param managerId  the value for departments.manager_id
	 * @mbg.generated
	 */
	public void setManagerId(Integer managerId) {
		this.managerId = managerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column departments.location_id
	 * @return  the value of departments.location_id
	 * @mbg.generated
	 */
	public Integer getLocationId() {
		return locationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column departments.location_id
	 * @param locationId  the value for departments.location_id
	 * @mbg.generated
	 */
	public void setLocationId(Integer locationId) {
		this.locationId = locationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table departments
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", departmentId=").append(departmentId);
		sb.append(", departmentName=").append(departmentName);
		sb.append(", managerId=").append(managerId);
		sb.append(", locationId=").append(locationId);
		sb.append("]");
		return sb.toString();
	}
}